; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "GP Database"
#define MyAppVersion "3.0.1"
#define MyAppPublisher "Ngalah Developer"
#define MyAppURL "http://www.ngadep.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C909EEEE-992E-447A-9709-943E63D9973A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\GP_Database
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=GPDb_setup_mini
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Files]
Source: "BAHAN\unzipper.dll"; Flags: dontcopy
Source: "BAHAN\MySQL\_source\init_user_db.sql"; DestDir: "{tmp}"; DestName: "UTjh987lOHi56.dat"; Flags: ignoreversion
Source: "BAHAN\MySQL\_source\AllStrukture.sql"; DestDir: "{tmp}"; DestName: "RK56lrUR34i56.dat"; Flags: ignoreversion; AfterInstall: ExtractMySQL;

[Run]

[Code]
procedure unzip(src, target: AnsiString);
external 'unzip@files:unzipper.dll stdcall delayload';

procedure ExtractMySQL;
begin
  Log(ExpandConstant('{src}\mysql.zip'));
  if FileExists(ExpandConstant('{src}\mysql.zip')) then
  begin
    Log('Extract ' + ExpandConstant('{src}\mysql.zip'));
    unzip(ExpandConstant('{src}\mysql.zip'), ExpandConstant('{app}'));
  end;
end;